[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]
evm_version = "shanghai"
optimizer = true
optimizer_runs = 2000
# solc = 0.8.9
# See more config options https://github.com/foundry-rs/foundry
