name: Integration Tests
#on: [ push ]
#
#jobs:
#  test_hardhat_integration_fork:
#    name: Hardhat / Holesky Devnet 0
#    runs-on: ubuntu-latest
#    timeout-minutes: 120
#
#    services:
#      hardhat-node:
#        image: ghcr.io/lidofinance/hardhat-node:2.22.12
#        ports:
#          - 8555:8545
#        env:
#          ETH_RPC_URL: "${{ secrets.HOLESKY_RPC_URL }}"
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Common setup
#        uses: ./.github/workflows/setup
#
#      - name: Set env
#        run: cp .env.example .env
#
#      - name: Run integration tests
#        run: yarn test:integration:fork:holesky:vaults:dev0
#        env:
#          LOG_LEVEL: debug
